#### basic imports

In [28]:
# python version 3.11.0
import numpy as np

#### 1. np.array()

In [29]:
# create an array of given input
simple_array = np.array([1, 2, 3, 4, 5])
print(simple_array)

[1 2 3 4 5]


#### 2. np.zeros()

In [30]:
# simply create an array of 10 with every element as being 0
zero_array = np.zeros(10)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. np.ones()

In [31]:
# simply create an array of 10 with every element being 1
one_array = np.ones(10)
print(one_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 4. np.reshape()

In [47]:
# simply reshape the array according to input if possible
simple_array = np.array([1, 2, 3, 4, 5])
print("shape of orignal array: ", simple_array.shape,'\n') # 1 row, 5 columns
new_array = simple_array.reshape(5,1)
print("new array: ", new_array,'\n')
print("shape of new array: ", new_array.shape) # 5 rows, 1 column
another_array = np.array([1, 2, 3, 4, 5, 6])
print("shape of another array: ", another_array.shape,'\n') # 1 row, 6 columns
another_new_array = another_array.reshape(2,3)
print("another new array: ", another_new_array,'\n')
print("shape of another new array: ", another_new_array.shape) # 2 rows, 3 columns

shape of orignal array:  (5,) 

new array:  [[1]
 [2]
 [3]
 [4]
 [5]] 

shape of new array:  (5, 1)
shape of another array:  (6,) 

another new array:  [[1 2 3]
 [4 5 6]] 

shape of another new array:  (2, 3)


#### 5. np.concatenate()

In [51]:
# simply conacate two arrays sequence wise and column wise if axis is given as 1
first_array = np.array([1, 2, 3, 4, 5])
second_array = np.array([6, 7, 8, 9, 10])
final_array = np.concatenate((first_array, second_array))
print("concatenated array: ",final_array)
new_first_array = first_array.reshape(5,1)
new_second_array = second_array.reshape(5,1)
new_final_array = np.concatenate((new_first_array, new_second_array), axis=1)   # axis=1 means concatenate along columns not simple concatenation with sequence
print("new concatenated array: ",new_final_array)

concatenated array:  [ 1  2  3  4  5  6  7  8  9 10]
new concatenated array:  [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


#### 6. np.mean()

In [48]:
# simply calculates mean of the array
simple_array = np.array([1, 2, 3, 4, 5])
mean = np.mean(simple_array)
print(mean)
simple_array = np.ones(10)
mean = np.mean(simple_array)
print(mean)

3.0
1.0


#### 7. np.sum()

In [37]:
# simply does the sum of every element in the array
simple_array = np.array([1, 2, 3, 4, 5])
sum = np.sum(simple_array)
print(sum)

15


#### 8. np.min()

In [38]:
# simply find the minimum value in the array
simple_array = np.array([1, 2, 3, 4, 5])
min = np.min(simple_array)
print(min)

1


#### 9. np.max()

In [39]:
# simply finds the maximum value in the array
simple_array = np.array([1, 2, 3, 4, 5])
max = np.max(simple_array)
print(max)

5


#### 10. np.argmax()

In [40]:
# simply finds the position of the maximum value in the array
simple_array = np.array([1, 2, 3, 4, 5])
argmax = np.argmax(simple_array)
print(argmax)

4


#### 11. np.argmin()

In [41]:
# simply finds the position of the minimum value in the array
simple_array = np.array([1, 2, 3, 4, 5])
argmin = np.argmin(simple_array)
print(argmin)

0


#### 12. np.random.rand()

In [57]:
# simply creates an array of given dimention with random values from [0,1) with uniform distribution
random_array = np.random.rand(1, 10)
print(random_array)

[[0.88543375 0.26082813 0.60159586 0.91265112 0.88710219 0.01177819
  0.58014957 0.90286359 0.3140816  0.03211913]]


#### 13. np.random.randn()

In [58]:
# simply creates an array of given dimention with random values with standard normal distribution
random_array = np.random.randn(1, 10)
print(random_array)

[[-0.74867288 -0.02088257 -0.3178342   0.7662589  -1.66853937  0.32461019
   1.59375689  0.76122732  0.08456865  0.71024295]]


#### 14. np.random.randint()

In [70]:
# simply creates an array of given minimum, maximum input, shape and data type
random_array = np.random.randint(10,size=(5,5),dtype=int)
print(random_array)

[[5 2 5 4 8]
 [6 4 6 8 8]
 [5 1 3 0 1]
 [1 7 1 0 6]
 [5 5 2 0 0]]


#### 15. np.dot()

In [55]:
# simply performs dot product of two input arrays
first_array = np.array([1, 2, 3, 4, 5])
second_array = first_array.reshape(5,1)
dot_product = np.dot(first_array, second_array)
print("dot product of 1 x 5 and 5 x 1 matrix : ",dot_product,'\n')
another_array = np.array([1, 2, 3, 4, 5, 6])
another_new_array = another_array.reshape(2,3)
another_array = another_array.reshape(3,2)
dot_product = np.dot(another_new_array, another_array)
print("dot product of 2 x 3 and 3 x 2 matrix : ",dot_product)

dot product of 1 x 5 and 5 x 1 matrix :  [55] 

dot product of 2 x 3 and 3 x 2 matrix :  [[22 28]
 [49 64]]
